apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base # relative path to the base folder

resources:
  - pvc.yaml # a new resource

patchesStrategicMerge:
  - deployment.yaml
  - service.yaml